spawn:
  interval-seconds: 300
  chance-per-interval: 0.35
  max-active: 2
  min-distance-from-player: 20
  max-distance-from-player: 60
  entity-type: VILLAGER

drops:
  parts-per-kill: 1

launch:
  ascent-ticks: 80
  ascent-step: 0.35
  explosion-power: 6.0
  show-firework: true

skin:
  player-name: kimyou12345

models:
  missile-custom-model-data: 5010
  launchpad-custom-model-data: 5011
  missile-nose-custom-model-data: 5001
  missile-body-custom-model-data: 5002
  missile-engine-custom-model-data: 5003
  launchpad-base-custom-model-data: 5004
  launchpad-control-custom-model-data: 5005
  launchpad-support-custom-model-data: 5006
  player-skin-custom-model-data: 5012
