name: Just Stop Oil

on:
  push:
    branches: ["main", "develop"]
    paths: ["just-stop-oil/**"]
  pull_request:
    paths: ["just-stop-oil/**"]

jobs:
  test-just-stop-oil:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Run tests
        run: mvn -f just-stop-oil/pom.xml test
      - name: Package jar
        run: mvn -f just-stop-oil/pom.xml -DskipTests package
      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: just-stop-oil-jar
          path: just-stop-oil/target/just-stop-oil-1.0.0.jar

  deploy-testing:
    runs-on: ubuntu-latest
    needs: test-just-stop-oil
    if: github.event_name == 'pull_request'
    environment: testing
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: just-stop-oil-jar
          path: dist
      - name: Upload jar to production server
        env:
          SFTP_USERNAME: ${{ vars.SFTP_USERNAME }}
          SFTP_URL: ${{ vars.SFTP_URL }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          SFTP_PORT: ${{ vars.SFTP_PORT }}
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: $SFTP_URL
          username: $SFTP_USERNAME
          password: $SFTP_PASSWORD
          port: $SFTP_PORT
          uploads: |
           ./dist/ => ./plugins/
  deploy-production:
    runs-on: ubuntu-latest
    needs: test-just-stop-oil
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: just-stop-oil-jar
          path: dist
      - name: Upload jar to production server
        env:
          SFTP_USERNAME: ${{ vars.SFTP_USERNAME }}
          SFTP_URL: ${{ vars.SFTP_URL }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          SFTP_PORT: ${{ vars.SFTP_PORT }}
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: $SFTP_URL
          username: $SFTP_USERNAME
          password: $SFTP_PASSWORD
          port: $SFTP_PORT
          uploads: |
           ./dist/ => ./plugins/
